import "./globals.css";
import { Outfit, Poppins, Inter } from "next/font/google";
import Navbar from "@/components/Navbar";

const outfit = Outfit({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"], // Specify subsets as needed
  variable: "--font-outfit",
});

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"], // Specify subsets as needed
  variable: "--font-poppins",
});

const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"], // Specify subsets as needed
  variable: "--font-inter",
});


export const metadata = {
  title: "Orphan Oldage Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scrollbar-thin scrollbar-thumb-[#A0FFBA] scrollbar-track-[#263238] ">
      <body className={`${outfit.variable} ${poppins.variable} ${inter.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
